default:
  domains: ['mylab.com.br']
  py_docker_configs: '/configs/'
  py_docker_functions: '/functions/'
  py_docker_templates: '/templates/'

networks:
  - name: 'netapps'
    subnet: '172.254.0.0/16'
    gateway: '172.254.0.254'
    driver: 'bridge'

apps:
  - name: 'HAProxy'
    base_image: 'haproxy:1.7'
    network: 'netapps'
    ip: '172.254.0.253'
    aliases: ["haproxy-apps"]
    image: 'haproxy_apps:v1.0'
    ports: [80]
    port_bindings: '{"80":80}'
    dockerfile_path: '/configs/haproxy_nginx/'
    dockerfile: 'Dockerfile'
    tag: 'haproxy_apps:v1.0'
    template: true
    template_file: 'Dockerfile.haproxy'
    backend: false
    volumes: ['haproxy;/usr/local/etc/haproxy:ro']
    active: true
  - name: 'app1'
    base_image: 'centos:latest'
    network: 'netapps'
    ip: '172.254.0.1'
    aliases: ["app1", "app1.mylab.com.br"]
    image: 'app1:v1.0'
    ports: [80]
    port_bindings: '{"80":8081}'
    dockerfile_path: '/configs/app1/'
    dockerfile: 'Dockerfile'
    tag: 'app1:v1.0'
    template: true
    template_file: 'Dockerfile.apps'
    backend: true
    volumes: ['html;/var/www/html:ro']
    active: true
  - name: 'app2'
    base_image: 'centos:latest'
    network: 'netapps'
    ip: '172.254.0.2'
    aliases: ["app2", "app2.mylab.com.br"]
    image: 'app2:v1.0'
    ports: [80]
    port_bindings: '{"80":8082}'
    dockerfile_path: '/configs/app2/'
    dockerfile: 'Dockerfile'
    tag: 'app2:v1.0'
    template: true
    template_file: 'Dockerfile.apps'
    backend: true
    volumes: ['html;/var/www/html:ro']
    active: true
  - name: 'app3'
    base_image: 'centos:latest'
    network: 'netapps'
    ip: '172.254.0.3'
    aliases: ["app3", "app3.mylab.com.br"]
    image: 'app3:v1.0'
    ports: [80]
    port_bindings: '{"80":8083}'
    dockerfile_path: '/configs/app3/'
    dockerfile: 'Dockerfile'
    tag: 'app3:v1.0'
    template: true
    template_file: 'Dockerfile.apps'
    backend: true
    volumes: ['html;/var/www/html:ro']
    active: false