default:
  domain: '.mylab.com.br'
  py_docker_configs: '/configs/'
  py_docker_functions: '/functions/'
  py_docker_templates: '/templates/'

networks:
  - name: 'netapps'
    subnet: '172.254.0.0/16'
    gateway: '172.254.0.254'
    driver: 'bridge'

apps:
  - name: 'proxy_nginx'
    network: 'netapps'
    ip: '172.254.0.253'
    aliases: ["proxy-apps"]
    image: 'proxy_apps:v1.0'
    ports: [80]
    port_bindings: '{80:80}'
    dockerfile_path: '/configs/proxy_nginx/'
    dockerfile: 'Dockerfile'
    tag: 'proxy_apps:v1.0'
    template: true
  - name: 'app1'
    network: 'netapps'
    ip: '172.254.0.1'
    aliases: ["app1", "app1.mylab.com.br"]
    image: 'app1:v1.0'
    ports: [80]
    port_bindings: '{80:8081}'
    dockerfile_path: '/configs/app1/'
    dockerfile: 'Dockerfile'
    tag: 'app1:v1.0'
  - name: 'app2'
    network: 'netapps'
    ip: '172.254.0.2'
    aliases: ["app2", "app2.mylab.com.br"]
    image: 'app2:v1.0'
    ports: [80]
    port_bindings: '{80:8082}'
    dockerfile_path: '/configs/app2/'
    dockerfile: 'Dockerfile'
    tag: 'app2:v1.0'