FROM	{{ base_image }}

LABEL	{{ app_name }}.vendor="Andre L S Ferreira" \
		{{ app_name }}.description="MeetUP DevOPs 2."

RUN apt update\
	&& apt install haproxy vim net-tools iputils-ping -y \
	&& echo "ENABLED=1" > /etc/default/haproxy

ADD ./haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

#ENTRYPOINT ["/etc/init.d/haproxy", "start"]